import { MaskType, RegularExp } from 'src/types/general'

export const maskedInput: Partial<MaskType> = {
  pasaporte: [
    /[A-Z a-z]?/,
    /[A-Z a-z]?/,
    /[A-Z a-z]?/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /[1,9]/,
  ],
  cedula: [
    /\d/,
    /\d/,
    /\d/,
    '-',
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    '-',
    /\d/,
  ],
  phone: [
    '(',
    /\d/,
    /\d/,
    /\d/,
    ')',
    ' ',
    /\d/,
    /\d/,
    /\d/,
    ' ',
    /\d/,
    /\d/,
    /\d/,
    /\d/,
  ],
  extension: [/\d/, /\d/, /\d/, /\d/],
  rnc: [/\d/, '-', /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/, /\d/, '-', /\d/],
  email: [/^\d^/],
  date: [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/],
}

export const regexp: Record<RegularExp, [RegExp, string] | RegExp | string> = {
  CUDULA: [/(\d{3})(\d{7})(\d)/, '$1-$2-$3'],
  RNC: [/(\d)(\d{2})(\d{5})(\d)/, '$1-$2-$3-$4'],
  PASSPORT: [/(\w{2})(\d{7})/, '$1-$2'],
  ACCOUNT: [/(\d{3})(\d{3})(\d{7})(\d)/, '$1-$2-$3-$4'],
  PHONE_INT: [/(\d{3})(\d{3})(\d{4})(\d{3})/, '$1 $2 $3 $4'],
  PHONE_DOM: [/(\d{3})(\d{3})(\d{4})/, '($1) $2 $4'],
  BOOK_FOLIO_ACT: [/(\d{5})(\d{4})(\d+)/, '$1-$2-$3'],
  EMAIL: '',
}
